Agenda.MVC/Controllers/AgendaAdminController.cs
using Agenda.MVC.API;
using Agenda.MVC.ViewModels;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Agenda.MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AgendaAdminController : Controller
    {
        private readonly HttpService _httpService;
        private readonly IMapper _mapper;

        public AgendaAdminController(HttpService httpService, IMapper mapper)
        {
            _httpService = httpService;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<ActionResult> Index(AgendaViewModel vm, int page = 1)
        {
            var skip = vm.Take * (page - 1);
            var query = new BaseParams { Prop = vm.Search.Prop, Value = vm.Search.Value, Skip = skip, Take = vm.Take };

            var result = await _httpService.GetAdminContactsAsync(query);

            vm.AdminContacts = result;
            vm.TotalPages = (result.Total / query.Take) + 1;
            vm.CurrentPage = page;

            return View(vm);
        }

        [HttpGet]
        public async Task<ActionResult> Form(int? id = null)
        {
            await SetAllUsersSelectList();
            await SetPhoneTypesSelectList();

            if (!id.HasValue)
                return View(new AdminContactFormViewModel());

            var contact = await _httpService.GetAdminContactByIdAsync((int)id);
            if (contact == null)
                return NotFound();

            var model = _mapper.Map<AdminContactFormViewModel>(contact);

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Form(
            AdminContactFormViewModel form,
            string option = "Save"
            )
        {
            if (option.Contains("AddPhone"))
            {
                ModelState.Clear();
                form.Phones.Add(new PhoneFormViewModel());
            }

            if (option.Contains("RemovePhone"))
            {
                var split = option.Split("|");
                ModelState.Clear();
                form.Phones.Remove(form.Phones[int.Parse(split[1])]);
            }

            if (option.Contains("Save"))
            {
                var result = form.Id.HasValue ?
                    await _httpService.UpdateAdminContactAsync(form) :
                    await _httpService.AddAdminContactAsync(form);

                if (result.HasError)
                {
                    result.AddErrorsToModelState(ModelState);
                }
                else
                {
                    TempData.Add("toast", "Contact created with success!");
                    return RedirectToAction(nameof(Index));
                }
            }
            await SetPhoneTypesSelectList();
            await SetAllUsersSelectList();
            return View(form);
        }

        [HttpGet]
        public async Task<ActionResult> Remove(int id)
        {
            await _httpService.RemoveAdminContactAsync(id);
            TempData.Add("toast", "Contact removed with success!");
            return RedirectToAction(nameof(Index));
        }

        private async Task SetPhoneTypesSelectList()
        {
            var types = await _httpService.GetPhoneTypesAsync();
            var list = new SelectList(types, "Id", "Name");
            ViewBag.PhoneTypes = list;
        }

        private async Task SetAllUsersSelectList()
        {
            var users = await _httpService.GetAllUsersAsync();
            var items = users.Select(x => new
            {
                Text = $"{x.Name} - {x.Username}",
                Id = x.Id
            })
            .ToList();

            ViewBag.Users = new SelectList(items, "Id", "Text");
        }
    }
}

Agenda.MVC/Controllers/AgendaController.cs
using Agenda.MVC.API;
using Agenda.MVC.ViewModels;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Agenda.MVC.Controllers
{
    [Authorize]
    public class AgendaController : Controller
    {
        private readonly HttpService _httpService;
        private readonly IMapper _mapper;

        public AgendaController(HttpService httpService, IMapper mapper)
        {
            _httpService = httpService;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<ActionResult> Index(AgendaViewModel vm, int page = 1)
        {
            var skip = vm.Take * (page - 1);
            var query = new BaseParams { Prop = vm.Search.Prop, Value = vm.Search.Value, Skip = skip, Take = vm.Take };

            var result = await _httpService.GetContactsAsync(query);

            vm.Contacts = result;
            vm.TotalPages = (result.Total / query.Take) + 1;
            vm.CurrentPage = page;

            return View(vm);
        }

        [HttpGet]
        public async Task<ActionResult> Form(int? id = null)
        {
            await SetPhoneTypesSelectList();

            if (!id.HasValue)
                return View(new AdminContactFormViewModel());

            var contact = await _httpService.GetContactByIdAsync((int)id);
            if (contact == null)
                return NotFound();

            var model = _mapper.Map<ContactFormViewModel>(contact);

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Form(
            ContactFormViewModel form,
            string option = "Save"
            )
        {
            if (option.Contains("AddPhone"))
            {
                ModelState.Clear();
                form.Phones.Add(new PhoneFormViewModel());
            }

            if (option.Contains("RemovePhone"))
            {
                var split = option.Split("|");
                ModelState.Clear();
                form.Phones.Remove(form.Phones[int.Parse(split[1])]);
            }

            if (option.Contains("Save"))
            {
                var result = form.Id.HasValue ?
                    await _httpService.UpdateContactAsync(form) :
                    await _httpService.AddContactAsync(form);

                if (result.HasError)
                {
                    result.AddErrorsToModelState(ModelState);
                }
                else
                {
                    TempData.Add("toast", "Contact created with success!");
                    return RedirectToAction(nameof(Index));
                }
            }
            await SetPhoneTypesSelectList();
            return View(form);
        }

        [HttpGet]
        public async Task<ActionResult> Remove(int id)
        {
            await _httpService.RemoveContactAsync(id);
            TempData.Add("toast", "Contact removed with success!");
            return RedirectToAction(nameof(Index));
        }

        private async Task SetPhoneTypesSelectList()
        {
            var types = await _httpService.GetPhoneTypesAsync();
            var list = new SelectList(types, "Id", "Name");
            ViewBag.PhoneTypes = list;
        }
    }
}

Agenda.MVC/Controllers/LoginController.cs
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using Agenda.MVC.API;
using Agenda.MVC.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;

namespace Agenda.MVC.Areas.Login.Controllers
{
    public class LoginController : Controller
    {
        private readonly HttpService _httpService;

        public LoginController(HttpService httpService)
        {
            _httpService = httpService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(LoginViewModel loginViewModel)
        {
            var token = await _httpService.LoginAsync(loginViewModel);

            if (token == null)
            {
                ModelState.AddModelError(string.Empty, "Invalid username or password!");
                return View(loginViewModel);
            }

            await LoginCookie(new ClaimsIdentity(
                DecodeToken(token),
                CookieAuthenticationDefaults.AuthenticationScheme,
                "name",
                "role"));

            return Redirect(Url.Action("Index", "Home"));
        }

        [HttpGet]
        public async Task<ActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return Redirect(Url.Action("Index"));
        }

        private IEnumerable<Claim> DecodeToken(string token)
        {
            var handler = new JwtSecurityTokenHandler();
            var decodedToken = handler.ReadJwtToken(token);
            var list = new List<Claim>(){new Claim("jwt-token", token)};
            list.AddRange(decodedToken.Claims);
            return list;
        }

        private async Task LoginCookie(ClaimsIdentity claimsIdentity)
        {
            var authProperties = new AuthenticationProperties
            {
                //AllowRefresh = <bool>,
                // Refreshing the authentication session should be allowed.
                // NUNCA MAIOR DO QUE O TEMPO DO TOKEN
                ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(99),
                // The time at which the authentication ticket expires. A
                // value set here overrides the ExpireTimeSpan option of
                // CookieAuthenticationOptions set with AddCookie.

                IsPersistent = true,
                // Whether the authentication session is persisted across
                // multiple requests. When used with cookies, controls
                // whether the cookie's lifetime is absolute (matching the
                // lifetime of the authentication ticket) or session-based.

                //IssuedUtc = <DateTimeOffset>,
                // The time at which the authentication ticket was issued.

                RedirectUri = "/"
                // The full path or absolute URI to be used as an http
                // redirect response value.
            };

            await HttpContext.SignInAsync(
                new ClaimsPrincipal(claimsIdentity),
                authProperties);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Agenda.MVC/Controllers/UsersController.cs
using Agenda.MVC.API;
using Agenda.MVC.ViewModels;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Agenda.MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly HttpService _httpService;
        private readonly IMapper _mapper;

        public UsersController(HttpService httpService, IMapper mapper)
        {
            _httpService = httpService;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<ActionResult> Index(UserPaginationViewModel vm, int page = 1)
        {
            var skip = vm.Take * (page - 1);
            var query = new BaseParams { Prop = vm.Search.Prop, Value = vm.Search.Value, Skip = skip, Take = vm.Take };

            var result = await _httpService.GetUsersAsync(query);

            vm.Users = result;
            vm.TotalPages = (result.Total / query.Take) + 1;
            vm.CurrentPage = page;

            return View(vm);
        }

        [HttpGet]
        public async Task<ActionResult> Form(int? id = null)
        {
            await SetUserRolesSelectList();

            if (!id.HasValue)
                return View(new UserFormViewModel());

            var user = await _httpService.GetUserByIdAsync((int)id);
            if (user == null)
                return NotFound();

            var model = _mapper.Map<UserFormViewModel>(user);

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Form(
            UserFormViewModel form,
            string option = "Save"
            )
        {
            if (option.Contains("Save"))
            {
                var result = form.Id.HasValue ?
                    await _httpService.UpdateUserAsync(form) :
                    await _httpService.AddUserAsync(form);

                if (result.HasError)
                {
                    result.AddErrorsToModelState(ModelState);
                }
                else
                {
                    TempData.Add("toast", "User created with success!");
                    return RedirectToAction(nameof(Index));
                }
            }
            await SetUserRolesSelectList();
            return View(form);
        }

        [HttpGet]
        public async Task<ActionResult> Remove(int id)
        {
            await _httpService.RemoveUserAsync(id);
            TempData.Add("toast", "User removed with success!");
            return RedirectToAction(nameof(Index));
        }

        private async Task SetUserRolesSelectList()
        {
            var roles = await _httpService.GetUserRolesAsync();
            var list = new SelectList(roles, "Id", "Name");
            ViewBag.roles = list;
        }
    }
}

Agenda.MVC/Views/Shared/_Header.cshtml
@using System.Security.Claims

<link href="~/css/Header.css" rel="stylesheet" type="text/css" asp-append-version="true" />

<div class="header">
  <a class="logo" asp-controller="Home" asp-action="Index"><img src="@Url.Content("~/img/logohome.png")" width="150" height="40" alt="logo"></img></a>

  <div class="log-container">
    @if (User.Identity.IsAuthenticated)
    {
      <div class="log-container">
        <div class="username">
          <p>@User.Claims.FirstOrDefault(x => x.Type.Equals("Email", StringComparison.OrdinalIgnoreCase))?.Value</p>
        </div>
        <a asp-controller="Login" asp-action="Logout" class="logout-btn">
          <p>Logout</p>
        </a>
      </div>
    }
    else
    {
      <a asp-controller="Login" asp-action="Index" class="login-btn">
        <p>Log In</p>
      </a>

      <a href="/register" class="signup-btn">
        <p>Sign Up</p>
      </a>
    }
  </div>
</div>

@section Scripts {
  @await Html.PartialAsync("_ValidationScriptsPartial")
}

Agenda.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Agenda</title>
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/Agenda.MVC.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/lib/font-awesome/css/fontawesome.css" />
  @RenderSection("Styles", false)
</head>
<body>
	<header>
    @await Html.PartialAsync("_Header.cshtml")
	</header>
	<div class="container">
		<main>
			@RenderBody()
		</main>
    <aside>
      @await Html.PartialAsync("_Navigation.cshtml")
    </aside>
	</div>

	<script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
  <script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)

  @if(TempData.TryGetValue("toast", out var msg))
  {
    <script>
      document.addEventListener('DOMContentLoaded', function() {
        M.toast({html: '@Html.Raw(msg)'})
      });
    </script>
  }
</body>
</html>

Agenda.MVC/Views/Shared/_Navigation.cshtml
@using System.Security.Claims

<link href="~/css/navigation.css" rel="stylesheet" type="text/css" asp-append-version="true" />

<div class="nav-wrapper">
  <div class="nav-display">
    <p>Manage</p>
  </div>
  @if(User.IsInRole("Admin"))
  {
    <a asp-controller="Users" asp-action="Index" class="users">
    <p>Users</p>
    </a>
    <a  asp-controller="AgendaAdmin" asp-action="Index" class="admin-contacts">
      <p>Admin Contacts</p>
    </a>
  }

  <a asp-controller="Agenda" asp-action="Index" class="contacts">
    <p>Contacts</p>
  </a>

  <div class="nav-display">
    <p>About</p>
  </div>
  <div class="about">
    <p>© 2022 Created by Marcelo Wesley<br> from Luby.Software</p>
  </div>
</div>

Agenda.MVC/Views/Shared/_PhoneFormPartial.cshtml
@model ContactFormViewModel

@for (var i = 0; i < Model!.Phones.Count(); i++)
{
    <button type="submit" name="option" class="btn-remove-phone" value="RemovePhone|@i">
      x
    </button>
    <div class="form-section">
      @Html.LabelFor(x => x.Phones[i].FormattedNumber, new { @class = "label-display"})
      @Html.TextBoxFor(x => x.Phones[i].FormattedNumber, htmlAttributes: new { placeholder = "Number", @class = "input2" })
      @Html.ValidationMessageFor(x => x.Phones[i].FormattedNumber, "", new { @class = "validation-msg" })
    </div>
    <div class="form-section">
      @Html.LabelFor(x => x.Phones[i].Description, new { @class = "label-display"})
      @Html.TextBoxFor(x => x.Phones[i].Description, htmlAttributes: new { placeholder = "Description", @class = "input2" })
      @Html.ValidationMessageFor(x => x.Phones[i].Description, "", new { @class = "validation-msg" })
    </div>
    <div class="form-section">
      @Html.LabelFor(x => x.Phones[i].PhoneTypeId, new { @class = "label-display"})
      @Html.DropDownListFor(x => x.Phones[i].PhoneTypeId, (SelectList)ViewBag.PhoneTypes, htmlAttributes: new { @class = "input2"})
      @Html.ValidationMessageFor(x => x.Phones[i].PhoneTypeId)
    </div>
}